"""Initial migration

Revision ID: eba72bf2d1a2
Revises: 
Create Date: 2025-04-18 12:20:50.640535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba72bf2d1a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sponsor_approved', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('influencer_name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('niche', sa.String(length=100), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('goals', sa.Text(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('idx_campaign_sponsor_visibility', ['sponsor_id', 'visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_sponsor_id'), ['sponsor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_visibility'), ['visibility'], unique=False)

    op.create_table('ad_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('payment_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_offer_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ad_requests', schema=None) as batch_op:
        batch_op.create_index('idx_adrequest_campaign_influencer', ['campaign_id', 'influencer_id'], unique=False)
        batch_op.create_index('idx_adrequest_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_requests_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_requests_influencer_id'), ['influencer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_requests_initiator_id'), ['initiator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ad_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ad_requests_status'))
        batch_op.drop_index(batch_op.f('ix_ad_requests_initiator_id'))
        batch_op.drop_index(batch_op.f('ix_ad_requests_influencer_id'))
        batch_op.drop_index(batch_op.f('ix_ad_requests_campaign_id'))
        batch_op.drop_index('idx_adrequest_status')
        batch_op.drop_index('idx_adrequest_campaign_influencer')

    op.drop_table('ad_requests')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_visibility'))
        batch_op.drop_index(batch_op.f('ix_campaigns_sponsor_id'))
        batch_op.drop_index('idx_campaign_sponsor_visibility')

    op.drop_table('campaigns')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    # ### end Alembic commands ###
